pages:
- Home: 'index.md'
- Getting Started: 'getting-started.md'
- User Guide:
	- 'IO Control' : ' users-guide/board-control/io-control.md'
	- 'UEXT Expansion' : 'users-guide/board-control/uext-expansion.md'
	- 'Motor Usage' : 'users-guide/motor-control/motor-usage.md'
	- 'Motor Commands' : 'users-guide/motor-control/motor-commands.md'
	- 'Motor Settings' : 'users-guide/motor-control/motor-settings.md'
- About:
    - 'License': 'about/license.md'
